/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-10-02 20:43:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;

public final class webgeneric_005fadmin_005fpage_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private javax.servlet.jsp.tagext.JspFragment header;
  private javax.servlet.jsp.tagext.JspFragment leftMenu;
  private javax.servlet.jsp.tagext.JspFragment footer;

  public javax.servlet.jsp.tagext.JspFragment getHeader() {
    return this.header;
  }

  public void setHeader(javax.servlet.jsp.tagext.JspFragment header) {
    this.header = header;
    jspContext.setAttribute("header", header);
  }

  public javax.servlet.jsp.tagext.JspFragment getLeftMenu() {
    return this.leftMenu;
  }

  public void setLeftMenu(javax.servlet.jsp.tagext.JspFragment leftMenu) {
    this.leftMenu = leftMenu;
    jspContext.setAttribute("leftMenu", leftMenu);
  }

  public javax.servlet.jsp.tagext.JspFragment getFooter() {
    return this.footer;
  }

  public void setFooter(javax.servlet.jsp.tagext.JspFragment footer) {
    this.footer = footer;
    jspContext.setAttribute("footer", footer);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getHeader() != null ) 
      _jspx_page_context.setAttribute("header", getHeader());
    if( getLeftMenu() != null ) 
      _jspx_page_context.setAttribute("leftMenu", getLeftMenu());
    if( getFooter() != null ) 
      _jspx_page_context.setAttribute("footer", getFooter());

    try {
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("    <div id=\"pageheader\">\n");
      out.write("      ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getHeader() != null) {
        getHeader().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("      \n");
      out.write("      <div class=\"manager-header\">\n");
      out.write("\t  \t\n");
      out.write("\t  \t<div id=\"manager-manual-link\" onclick=\"window.open('html_manual/admin/Geoportal_Admin_Manual.html', '_blank ', 'location=no,menubar=no,titlebar=no,toolbar=no,resizable=yes,width=800,height=700')\" data-locale_key=\"Page_Manual_Switch_Button_Title\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\"><i class=\"fa fa-question fa-2x\"></i></div>\n");
      out.write("\t  \t<div id=\"manager-header-text\" data-locale_key=\"Manager_Header_Text\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t  \t\n");
      out.write("\t  </div>\n");
      out.write("\t  \n");
      out.write("    </div>\n");
      out.write("    <div id=\"container\" class=\"container\">\n");
      out.write("\t    <div id=\"leftMenu\">\n");
      out.write("\t      \t<div class=\"menu-left-manager\">\n");
      out.write("\t      \t\n");
      out.write("\t      \t");
 if (LoginService.currentUserHasPermission(session, Permissions.SYSTEM_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"system_config_menu\" data-locale_key=\"Manager_Item_ConfigSystem\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=system_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.GENERAL_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"general_config_menu\" data-locale_key=\"Manager_Item_ConfigGeneral\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=general_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t      \t");
 if (LoginService.currentUserHasPermission(session, Permissions.MAP_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"map_config_menu\" data-locale_key=\"Manager_Item_ConfigMaps\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=map_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.MAP_SETTING_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"map_setting_config_menu\" data-locale_key=\"Manager_Item_ConfigMapSettings\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=map_setting_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.LAYER_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"layer_config_menu\" data-locale_key=\"Manager_Item_ConfigLayers\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=layer_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.SOURCE_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"source_config_menu\" data-locale_key=\"Manager_Item_ConfigWMSSources\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=source_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.ALERTS_CONFIG_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"alert_config_menu\" data-locale_key=Manager_Item_ConfigAlert data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=alert_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.ROLE_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"role_config_menu\" data-locale_key=\"Manager_Item_ConfigRoles\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=role_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.USER_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"user_config_menu\" data-locale_key=\"Manager_Item_ConfigUsers\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=user_config'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.SHOW_LOGS_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"show_log_menu\" data-locale_key=\"Manager_Item_ShowLogs\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=show_logs'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 if (LoginService.currentUserHasPermission(session, Permissions.TEST_REQUESTS_ADMIN)) { 
      out.write("\n");
      out.write("\t\t\t\t<div id=\"test_requests_menu\" data-locale_key=\"Manager_Item_TestRequests\" data-locale_ref=\"text\" class=\"localizedElement menu-left-manager-item\" onclick=\"location.href = 'admin?page=test_requests'\"></div>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t    </div>\n");
      out.write("\t    \n");
      out.write("\t    <div class=\"center-container\">\n");
      out.write("\t      ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("\n");
      out.write("\t    </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"pagefooter\">\n");
      out.write("      ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getFooter() != null) {
        getFooter().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
