/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-10-02 21:48:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.LogService;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.SystemSettingService;

public final class admin_005fsystem_005fconfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/admin/admin_config_common_js.jspf", Long.valueOf(1506975243000L));
    _jspx_dependants.put("/WEB-INF/tags/generic_admin_page.tag", Long.valueOf(1506975243000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQueryUI CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jqueryui/jquery-ui-1.10.4/css/smoothness/jquery-ui-1.10.4.custom.css\" />\n");
      out.write("\n");
      out.write("<!-- JQueryUI -->\n");
      out.write("<script src=\"lib/jqueryui/jquery-ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQUERY Scrollbar -->\n");
      out.write("<script src=\"lib/scrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MD5 -->\n");
      out.write("<script src=\"lib/md5/md5.js\"></script>\n");
      out.write("\n");
      out.write("<!-- DATATABLE -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/datatable/datatable-1.10.2/css/jquery.dataTables.min.css\" />\n");
      out.write("<script src=\"lib/datatable/datatable-1.10.2/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/globals.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/manager.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- ICONS STYLE (FONT-AWESOME + EXTRA CUSTOM FONTS ICON) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-awesome.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-extra-icon.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!--Dragging secure Utils -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragging_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  Validator -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/validation/validation-1.13.1/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/validate/Validate.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Login -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/login/LoginUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- General Scripts -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/LoadingPanel.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/utils/Utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/Services.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/AlertDialog.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/DialogUtils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragdrop_utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/sorting_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Scripts - Locale -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/LocaleManager.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_en.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_es.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminMenu.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  General CSS -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/admin/general.css\" type=\"text/css\"> -->\n");
      out.write("<script>\n");

	/*
	* LANGUAGE
	*/
	String languageCode = LoginService.getCurrentLanguageFromSessionOrDefault(session);

	/*
	* GLOBAL VARIABLES
	*/
	 String jsonGlobalSettings = new SystemSettingService().getClientSystemSettingsAsJson();

      out.write("\n");
      out.write("var globalSystemSettingsJson =");
      out.print(jsonGlobalSettings);
      out.write(";\n");
      out.write("var GLOBAL_SETTINGS = globalSystemSettingsJson.result;\n");
      out.write("LocaleManager.setLocale(\"");
      out.print(languageCode);
      out.write("\");\n");
      out.write("\n");
      out.write("var AJAX_TIMEOUT = GLOBAL_SETTINGS.ajaxTimeout;\n");
      out.write("\n");
      out.write("</script>");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Manager System Configs scripts and CSS-->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/managerSystemSettings.css\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/systemSettings/managerSystemSettings.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Start script -->\n");
      out.write("<script>\n");
      out.write("\tvar validator = null;\n");
      out.write("\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tLocaleManager.refreshLocale();\n");
      out.write("\t\tAdminMenu.setSystemConfigPageActive();\n");
      out.write("\t\tmSystemSettings.requests.getData();\n");
      out.write("\t\t\n");
      out.write("\t\tvalidator = new Validate({\n");
      out.write("\t\t\tform: $(\"#systemAdminContainer\")\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#submit\").button();\n");
      out.write("\t\t$(\"#cancel\").button();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:generic_admin_page
    org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0 = (new org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspContext(_jspx_page_context);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_system_config.jsp(37,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setHeader(_jspx_temp0);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_system_config.jsp(37,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setFooter(_jspx_temp1);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null));
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<form id=\"systemAdminContainer\" onSubmit=\"return false;\">\t\t\n");
      out.write("\t\t\t<!-- <p>System Configuration - Global Settings.</p> -->\n");
      out.write("\t\t\t<!-- <p>Settings that apply to the entire system</p> -->\n");
      out.write("\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Title\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Subtitle\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_ProxyURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"proxy-input\" name=\"proxy-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_PrintServletURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"printservlet-url-input\" name=\"printservlet-url-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_PrintServletImagesFolder\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"printservlet-images-folder-input\" name=\"printservlet-images-folder-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_AlertsLegendImageURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"alerts-legend-imageurl-input\" name=\"alerts-legend-imageurl-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_RedlinesLegendImageURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"redlines-legend-imageurl-input\" name=\"redlines-legend-imageurl-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_GeoserverURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"geoserver-url-input\" name=\"geoserver-url-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_GeonetworkURL\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"geonetwork-url-input\"  name=\"geonetwork-url-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_MaxSearchFeaturePerLayer\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"max-num-feature-search-per-layer-input\" type=\"number\" name=\"max-num-feature-search-per-layer-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Selected_Layers_Max_Size\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"max-num-selected-layers-input\" type=\"number\" name=\"max-num-selected-layers-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_AjaxTimeOut\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"ajax-timeout-input\" type=\"number\" name=\"ajax-timeout-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_PrintAjaxTimeOut\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"ajax-timeout-print-input\" type=\"number\" name=\"ajax-timeout-print-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_HyperlinkField\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"featureInfoHyperlinkField-input\" name=\"featureInfoHyperlinkField-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Alerts_Title\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Alerts_Subtitle\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Alerts_Geoserver_Layername\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"alerts-geoserver-layername-input\" name=\"alerts-geoserver-layername-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Alerts_Geoserver_Username\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"alerts-geoserver-username-input\" name=\"alerts-geoserver-username-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_System_Alerts_Geoserver_Password\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"alerts-geoserver-password-input\" name=\"alerts-geoserver-password-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<button id=\"submit\" data-locale_key=\"General_Save\" data-locale_ref=\"text\" class=\"localizedElement\" onclick=\"mSystemSettings.requests.saveData();\"></button>\n");
      out.write("\t\t\t<button id=\"cancel\" data-locale_key=\"General_Cancel\" data-locale_ref=\"text\" class=\"localizedElement\" onclick=\"mSystemSettings.requests.getData();\"></button>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
