/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-10-03 16:19:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.LogService;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.SystemSettingService;

public final class admin_005fmap_005fsetting_005fconfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/admin/admin_config_common_js.jspf", Long.valueOf(1506975243000L));
    _jspx_dependants.put("/WEB-INF/tags/generic_admin_page.tag", Long.valueOf(1506975243000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQueryUI CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jqueryui/jquery-ui-1.10.4/css/smoothness/jquery-ui-1.10.4.custom.css\" />\n");
      out.write("\n");
      out.write("<!-- JQueryUI -->\n");
      out.write("<script src=\"lib/jqueryui/jquery-ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQUERY Scrollbar -->\n");
      out.write("<script src=\"lib/scrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MD5 -->\n");
      out.write("<script src=\"lib/md5/md5.js\"></script>\n");
      out.write("\n");
      out.write("<!-- DATATABLE -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/datatable/datatable-1.10.2/css/jquery.dataTables.min.css\" />\n");
      out.write("<script src=\"lib/datatable/datatable-1.10.2/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/globals.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/manager.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- ICONS STYLE (FONT-AWESOME + EXTRA CUSTOM FONTS ICON) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-awesome.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-extra-icon.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!--Dragging secure Utils -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragging_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  Validator -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/validation/validation-1.13.1/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/validate/Validate.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Login -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/login/LoginUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- General Scripts -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/LoadingPanel.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/utils/Utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/Services.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/AlertDialog.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/DialogUtils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragdrop_utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/sorting_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Scripts - Locale -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/LocaleManager.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_en.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_es.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminMenu.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  General CSS -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/admin/general.css\" type=\"text/css\"> -->\n");
      out.write("<script>\n");

	/*
	* LANGUAGE
	*/
	String languageCode = LoginService.getCurrentLanguageFromSessionOrDefault(session);

	/*
	* GLOBAL VARIABLES
	*/
	 String jsonGlobalSettings = new SystemSettingService().getClientSystemSettingsAsJson();

      out.write("\n");
      out.write("var globalSystemSettingsJson =");
      out.print(jsonGlobalSettings);
      out.write(";\n");
      out.write("var GLOBAL_SETTINGS = globalSystemSettingsJson.result;\n");
      out.write("LocaleManager.setLocale(\"");
      out.print(languageCode);
      out.write("\");\n");
      out.write("\n");
      out.write("var AJAX_TIMEOUT = GLOBAL_SETTINGS.ajaxTimeout;\n");
      out.write("\n");
      out.write("</script>");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Manager Map Settings scripts and CSS-->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/managerMapSettings.css\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/mapSettings/managerMapSettings.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Start script -->\n");
      out.write("<script>\n");
      out.write("\tvar validator = null;\n");
      out.write("\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tLocaleManager.refreshLocale();\n");
      out.write("\t\tAdminMenu.setMapSettingsConfigPageActive();\n");
      out.write("\t\tmMapSettings.requests.getData();\n");
      out.write("\t\t\n");
      out.write("\t\tvalidator = new Validate({\n");
      out.write("\t\t\tform: $(\"#mapSettingAdminContainer\")\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#submit\").button();\n");
      out.write("\t\t$(\"#cancel\").button();\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("#scales_buttons input, #scales_buttons div,\n");
      out.write("#resolutions_buttons input, #resolutions_buttons div {\n");
      out.write("\tfloat: left;\n");
      out.write("} \n");
      out.write("\n");
      out.write("#scales-add, #scales-delete,\n");
      out.write("#resolutions-add, #resolutions-delete {\n");
      out.write("/* \tpadding: 3px 3px 0px 3px !important; */\n");
      out.write("\tpadding: 1px 2px 0px 2px !important;\n");
      out.write("\tfont-size: 9px !important;\n");
      out.write("\tmargin-top: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scales-add, #resolution-add {\n");
      out.write("\tmargin-right: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scale-input, #resolution-input {\n");
      out.write("\tmargin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#list_scales, #list_resolutions {\n");
      out.write("\twidth: 368px;\n");
      out.write("\tword-wrap: break-word;\n");
      out.write("\tlist-style-type: none;\n");
      out.write("\tPADDING-LEFT: 0px;\n");
      out.write("\tmargin-top: 0px;\n");
      out.write("\tpadding-left: 300px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#list_scales .ui-selecting,\n");
      out.write("#list_resolutions .ui-selecting { background: #b0bed9; }\n");
      out.write("#list_scales .ui-selected,\n");
      out.write("#list_resolutions .ui-selected { background: #b0bed9; }\n");
      out.write("\t\n");
      out.write("#list_scales li,\n");
      out.write("#list_resolutions li {\n");
      out.write("\tmargin: 2px;\n");
      out.write("\tpadding: 0.4em;\n");
      out.write("\theight: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#radio_container {\n");
      out.write("\tpadding-top: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:generic_admin_page
    org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0 = (new org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspContext(_jspx_page_context);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_map_setting_config.jsp(89,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setHeader(_jspx_temp0);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_map_setting_config.jsp(89,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setFooter(_jspx_temp1);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null));
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<form id=\"mapSettingAdminContainer\" onSubmit=\"return false;\">\t\t\n");
      out.write("\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Title\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Subtitle\" data-locale_ref=\"text\" class=\"localizedElement\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Projection\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"projection-input\" name=\"projection-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Units\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"units-input\" name=\"units-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!--  DEFAULT ZOOMLEVEL & CENTER (OLD -->\n");
      out.write("<!-- \t\t\t<div class=\"itemform\"> -->\n");
      out.write("<!-- \t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_ZoomLevel\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div> -->\n");
      out.write("<!-- \t\t\t\t<div><input id=\"default-zoomlevel-input\" type=\"number\" name=\"default-zoomlevel-input\" required></div> -->\n");
      out.write("<!-- \t\t\t</div> -->\n");
      out.write("\t\t\t\n");
      out.write("<!-- \t\t\t<div class=\"itemform\"> -->\n");
      out.write("<!-- \t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Center_X\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div> -->\n");
      out.write("<!-- \t\t\t\t<div><input id=\"centerx-input\" type=\"number\" name=\"centerx-input\" required></div> -->\n");
      out.write("<!-- \t\t\t</div> -->\n");
      out.write("\t\t\t\n");
      out.write("<!-- \t\t\t<div class=\"itemform\"> -->\n");
      out.write("<!-- \t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Center_Y\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div> -->\n");
      out.write("<!-- \t\t\t\t<div><input id=\"centery-input\" type=\"number\" name=\"centery-input\" required></div> -->\n");
      out.write("<!-- \t\t\t</div> -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!--  DEFAULT EXTENT -->\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_Extent_MinX\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"minx-input\" name=\"minx-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_Extent_MinY\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"miny-input\" name=\"miny-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_Extent_MaxX\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"maxx-input\" name=\"maxx-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_Extent_MaxY\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"maxy-input\" name=\"maxy-input\" required></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Default_MaxScale\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"default-maxscale-input\" name=\"default-maxscale-input\" ></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=Manager_Map_Settings_Enable_CustomScalesResolutions data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div id=\"radio_container\">\n");
      out.write("\t\t\t\t\t<div style=\"width:50px !important; padding: 3px 5px 0 0;\">\n");
      out.write("\t\t\t\t\t\t<div style=\"width:20px !important;\" data-locale_key=Manager_Map_Settings_Enable_CustomScalesResolutions_None data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<input id=\"custom_sr_none\" type=\"radio\" value=\"none\"  name=\"enable_custom_scales_resolutions\" checked=\"checked\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;float: left;\">\n");
      out.write("\t\t\t\t\t\t<div style=\"width:50px !important; float: left !important;\" data-locale_key=Manager_Map_Settings_Enable_CustomScalesResolutions_Scales data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<input id=\"custom_sr_scales\" type=\"radio\" value=\"scales\"  name=\"enable_custom_scales_resolutions\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 10px;float: left;\">\n");
      out.write("\t\t\t\t\t\t<div style=\"width:85px !important;\" data-locale_key=Manager_Map_Settings_Enable_CustomScalesResolutions_Resolutions data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<input id=\"custom_sr_resolutions\" type=\"radio\" value=\"resolutions\"  name=\"enable_custom_scales_resolutions\">\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\" style=\"padding-top:7px\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_List_CustomScales\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div id=\"scales_buttons\">\n");
      out.write("\t\t\t\t\t<div style=\"width: 95px !important;\" data-locale_key=Manager_Map_Settings_Add_CustomScale data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t<input id=\"scale-input\" type=\"number\" name=\"scale-input\">\n");
      out.write("\t\t\t\t\t<div id=\"scales-add\" data-locale_key=\"Manager_Alerts_Types_Button_Add\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\" onclick=\"mMapSettings.addScale();\"><i class=\"fa fa-plus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t\t<div id=\"scales-delete\" data-locale_key=\"Manager_Alerts_Types_Button_Delete\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item custom-hidden\" onclick=\"mMapSettings.deleteScale();\"><i class=\"fa fa-minus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div class=\"form-label-title\"></div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<ol id=\"list_scales\">\n");
      out.write("\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"itemform\" style=\"padding-top:7px\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_List_CustomResolutions\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div id=\"resolutions_buttons\">\n");
      out.write("\t\t\t\t\t<div style=\"width: 95px !important;\" data-locale_key=Manager_Map_Settings_Add_CustomResolution data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t<input id=\"resolution-input\" type=\"number\" name=\"resolution-input\">\n");
      out.write("\t\t\t\t\t<div id=\"resolutions-add\" data-locale_key=\"Manager_Alerts_Types_Button_Add\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\" onclick=\"mMapSettings.addResolution();\"><i class=\"fa fa-plus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t\t<div id=\"resolutions-delete\" data-locale_key=\"Manager_Alerts_Types_Button_Delete\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item custom-hidden\" onclick=\"mMapSettings.deleteResolution();\"><i class=\"fa fa-minus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div class=\"form-label-title\"></div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<ol id=\"list_resolutions\">\n");
      out.write("\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Dots_Per_Inch_Override\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input id=\"dots-per-inch-input\" type=\"number\" name=\"dots-per-inch-input\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Show_Overview\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t<div><input type=\"checkbox\" id=\"show_overview\"  name=\"show_overview\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("<!-- \t\t\t<div class=\"itemform\"> -->\n");
      out.write("<!-- \t\t\t\t<div data-locale_key=\"Manager_Map_Settings_Show_Overview\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div> -->\n");
      out.write("<!-- \t\t\t\t<div><input id=\"show_overview\" type=\"checkbox\" name=\"show_overview\"></div> -->\n");
      out.write("<!-- \t\t\t</div> -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<button id=\"submit\" data-locale_key=\"General_Save\" data-locale_ref=\"text\" class=\"localizedElement\" onclick=\"mMapSettings.requests.saveData();\"></button>\n");
      out.write("\t\t\t<button id=\"cancel\" data-locale_key=\"General_Cancel\" data-locale_ref=\"text\" class=\"localizedElement\" onclick=\"mMapSettings.requests.getData();\"></button>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
