/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-10-03 17:10:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.SystemSettingService;

public final class admin_005flayer_005fconfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/admin/admin_config_common_js.jspf", Long.valueOf(1506975243000L));
    _jspx_dependants.put("/WEB-INF/tags/generic_admin_page.tag", Long.valueOf(1506975243000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Configuracion de Capas</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQueryUI CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jqueryui/jquery-ui-1.10.4/css/smoothness/jquery-ui-1.10.4.custom.css\" />\n");
      out.write("\n");
      out.write("<!-- JQueryUI -->\n");
      out.write("<script src=\"lib/jqueryui/jquery-ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQUERY Scrollbar -->\n");
      out.write("<script src=\"lib/scrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MD5 -->\n");
      out.write("<script src=\"lib/md5/md5.js\"></script>\n");
      out.write("\n");
      out.write("<!-- DATATABLE -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/datatable/datatable-1.10.2/css/jquery.dataTables.min.css\" />\n");
      out.write("<script src=\"lib/datatable/datatable-1.10.2/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/globals.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/manager.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- ICONS STYLE (FONT-AWESOME + EXTRA CUSTOM FONTS ICON) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-awesome.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-extra-icon.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!--Dragging secure Utils -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragging_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  Validator -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/validation/validation-1.13.1/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/validate/Validate.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Login -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/login/LoginUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- General Scripts -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/LoadingPanel.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/utils/Utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/Services.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/AlertDialog.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/DialogUtils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragdrop_utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/sorting_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Scripts - Locale -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/LocaleManager.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_en.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_es.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminMenu.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  General CSS -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/admin/general.css\" type=\"text/css\"> -->\n");
      out.write("<script>\n");

	/*
	* LANGUAGE
	*/
	String languageCode = LoginService.getCurrentLanguageFromSessionOrDefault(session);

	/*
	* GLOBAL VARIABLES
	*/
	 String jsonGlobalSettings = new SystemSettingService().getClientSystemSettingsAsJson();

      out.write("\n");
      out.write("var globalSystemSettingsJson =");
      out.print(jsonGlobalSettings);
      out.write(";\n");
      out.write("var GLOBAL_SETTINGS = globalSystemSettingsJson.result;\n");
      out.write("LocaleManager.setLocale(\"");
      out.print(languageCode);
      out.write("\");\n");
      out.write("\n");
      out.write("var AJAX_TIMEOUT = GLOBAL_SETTINGS.ajaxTimeout;\n");
      out.write("\n");
      out.write("</script>");
      out.write("\n");
      out.write("\n");
      out.write("<!--  Ajax Prefilter -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jqueryFilter/AjaxPrefilter.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Layer Config scripts and CSS-->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/managerLayers.css\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/layers/managerLayers.js\"></script>\n");
      out.write("\t\n");
      out.write("<!-- Capabilities support -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/openlayers/OpenLayers-2.13.1/OpenLayers.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/capabilities/getCapabilities.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("table.dataTable, table.dataTable th, table.dataTable td {\n");
      out.write("\twhite-space: normal !important;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- Start script -->\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\n");
      out.write("\t\tvar OL_PROXY_URL = GLOBAL_SETTINGS.proxyUrl;\n");
      out.write("\t\tAjaxPrefilter.activateProxyFilter(OL_PROXY_URL);\n");
      out.write("\t\t\n");
      out.write("\t\t/*\n");
      out.write("\t\t * Set the OpenLayers Proxy to bypass the Same Origin Policy issue.\n");
      out.write("\t\t */\n");
      out.write("\t\tOpenLayers.ProxyHost = OL_PROXY_URL;\n");
      out.write("\t\t\n");
      out.write("\t\tLocaleManager.refreshLocale();\n");
      out.write("\t\tAdminMenu.setLayerConfigPageActive();\n");
      out.write("\t\tUtils.enableTooltip();\n");
      out.write("\t\tmLayers.init();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t#layers-dt_wrapper {\n");
      out.write("\t  position: absolute;\n");
      out.write("\t  top: 50px;\n");
      out.write("\t  bottom: 0px;\n");
      out.write("\t  left: 0;\n");
      out.write("\t  right: 0px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#layers-dt_wrapper .dataTables_scroll {\n");
      out.write("\t  position: absolute;\n");
      out.write("\t  top: 30px;\n");
      out.write("\t  bottom: 0px;\n");
      out.write("\t  left: 0;\n");
      out.write("\t  right: 0px;\n");
      out.write("\t}\n");
      out.write("\t#layers-dt_wrapper .dataTables_scrollBody {\n");
      out.write("\t  overflow: auto;\n");
      out.write("\t  position: absolute;\n");
      out.write("\t  top: 55px;\n");
      out.write("\t  bottom: 0;\n");
      out.write("\t  height: auto !important;\n");
      out.write("\t  overflow: auto;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#layers-dt {\n");
      out.write("\t  width: 100%;\n");
      out.write("\t  position: absolute;\n");
      out.write("\t  bottom: 0px;\n");
      out.write("\t  top: 0px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#layers-dt_filter {\n");
      out.write("\t  padding-right: 6px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t<form id=\"form-dialog\" style=\"display:none\" onSubmit=\"return false;\">\n");
      out.write("\t\t<div id=\"form-dialog-header\" data-locale_key=\"Manager_Layers_HeaderForm_Add\" data-locale_ref=\"text\" class=\"localizedElement data-grid-form-header\"></div>\n");
      out.write("\t\t<input type=\"hidden\" id=\"layer-input-id\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"form-items-container\">\n");
      out.write("\t\t\t<div class=\"form-items-left\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\tDATOS DE IDENTIFICACION DE LA CAPA EN EL SERVIDOR \n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_Identification\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\t<!-- Fuente de la capa -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Source\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><select id=\"layer-select-source\" onchange=\"mLayers.layerSourceSelected();\"></select></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Nombre de la capa -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Name\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"layer-input-name\" name=\"layer-input-name\" required>\n");
      out.write("\t\t\t\t\t\t\t<button id=\"layer-load-wms\" data-locale_key=\"Manager_Layers_Button_NameFromWMS\" data-locale_ref=\"title\" class=\"localizedElement\" onclick=\"mLayers.loadLayersFromWMS();\"></button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\tDatos \"Descriptivos de la capa \n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_DataDescription\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\t<!-- Titulo de la capa -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Title\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-title\" name=\"layer-input-title\" required></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Description -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Desc\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div><textarea rows=\"5\" id=\"layer-input-desc\"></textarea></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Capa oficial? -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_isExternal data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-is-external\" name=\"layer-input-is-external\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- Responsible Party -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Responsible\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-responsible\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- Layer Reference Date -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_ReferenceDate data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-reference-date\" name=\"layer-input-reference-date\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\t\tENLACE A LOS METADATOS \n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_MetadataLink\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\t<!--  Metadata UUID -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_MetadataUUID\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-metadata_uuid\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  iMAGE FORMAT -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Format\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<select id=\"layer-select-format\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"image/png\">png</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"image/png8\">png8</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"image/jpeg\">jpeg</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_LayerAccessMode\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\t<!-- SLD -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_Override_SldUrl data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-attribute-override-sldurl\" name=\"layer-input-attribute-override-sldurl\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  SLD Url -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_SldUrl data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-attribute-sldurl\" name=\"layer-input-attribute-sldurl\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  Cache Url -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_CacheUrl\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input id=\"layer-input-cacheurl\" name=\"layer-input-cacheurl\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  Cache Workspace -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_CacheWorkspace\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input id=\"layer-input-cacheworkspace\" name=\"layer-input-cacheworkspace\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  Cache Enables -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_CacheEnabled\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-cacheEnabled\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Tiled -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Tiled\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-tiled\"></div>\n");
      out.write("\t<!-- \t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Tiled_Size_X\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div> -->\n");
      out.write("\t<!-- \t\t\t\t\t<div><input type=\"digits\" id=\"layer-input-tiled-sizex\" name=\"layer-input-tiled-sizex\" disabled></div> -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t<!-- \t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Tiled_Size_Y\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div> -->\n");
      out.write("\t<!-- \t\t\t\t\t<div><input type=\"digits\" id=\"layer-input-tiled-sizey\" name=\"layer-input-tiled-sizey\" disabled></div> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\t\tMODALIDAD DE PUBLICACION DE LA CAPA EN EL GEOPORTAL \n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_GeoportalLayerPublicationMode\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- baselayer -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Baselayer\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-baselayer\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- opacity -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_Opacity\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"layer-input-opacity\" class=\"item-slider-transparency\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Downloadable -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_isDownloadable data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-downloadable\" name=\"layer-input-downloadable\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- WFS Search enabled -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_WfsSearcheEnabled data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-wfsSearchEnabled\" name=\"layer-input-wfsSearchEnabled\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- Attribute Name for Info -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=Manager_Layers_Label_AttributeNameForInfo data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-attribute-name-for-info\" name=\"layer-input-attribute-name-for-info\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- SHOW INFO DIALOG -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_ShowInfoDialog\" data-locale_ref=\"text\" class=\"localizedElement form-label-title label-checkbox\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"checkbox\" id=\"layer-input-show_info_dialog\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\t\tDISTRIBUTION INFORMATION \n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t<legend data-locale_key=\"Manager_Layers_Fieldset_Legend_DistributionInfo\" data-locale_ref=\"text\" class=\"localizedElement\"></legend>\n");
      out.write("\t\t\t\t\t<!--  WFS URL -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_WfsUrl\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-wfs_url\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!--  WCS URL -->\n");
      out.write("\t\t\t\t\t<div class=\"itemform\">\n");
      out.write("\t\t\t\t\t\t<div data-locale_key=\"Manager_Layers_Label_WcsUrl\" data-locale_ref=\"text\" class=\"localizedElement form-label-title\"></div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" id=\"layer-input-wcs_url\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\t\n");
      out.write("\t<div id=\"form-del-dialog\"></div>\n");
      out.write("\t<div id=\"select-layer-fromwms\" style=\"display:none\">\n");
      out.write("\t\t<div data-locale_key=\"Manager_Layers_HeaderSelectLayerWms\" data-locale_ref=\"text\" class=\"localizedElement data-grid-form-header\"></div>\n");
      out.write("\t\t<div id=\"layer-list-wms\"></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:generic_admin_page
    org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0 = (new org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspContext(_jspx_page_context);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_layer_config.jsp(91,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setHeader(_jspx_temp0);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_layer_config.jsp(91,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setFooter(_jspx_temp1);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null));
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\t\t\t<div id=\"grid-container\">\n");
      out.write("\t\t\t\t<div class=\"data-grid-actions\">\n");
      out.write("\t\t\t\t\t<div id=\"layers-add\" data-locale_key=\"Manager_Layers_Button_Add\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\" onclick=\"mLayers.openAddForm();\"><i class=\"fa fa-plus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t\t<div id=\"layers-update\" data-locale_key=\"Manager_Layers_Button_Update\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\" onclick=\"mLayers.openUpdateForm();\"><i class=\"fa fa-edit fa-2x\"></i></div>\n");
      out.write("\t\t\t\t\t<div id=\"layers-delete\" data-locale_key=\"Manager_Layers_Button_Delete\" data-locale_ref=\"title\" class=\"localizedElement grid-toolbar-item\" onclick=\"mLayers.deleteLayer();\"><i class=\"fa fa-minus fa-2x\"></i></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<table id=\"layers-dt\"></table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
