/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-10-03 16:15:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.gesp.geoportal.services.MapConfigService;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.LogService;
import it.gesp.geoportal.locale.LocaleUtils;
import it.gesp.geoportal.services.LoginService;
import it.gesp.geoportal.constants.Permissions;
import it.gesp.geoportal.dao.entities.User;
import it.gesp.geoportal.services.SystemSettingService;

public final class admin_005ftest_005frequests_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/admin/admin_config_common_js.jspf", Long.valueOf(1506975243000L));
    _jspx_dependants.put("/WEB-INF/tags/generic_admin_page.tag", Long.valueOf(1506975243000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Pruebas de llamadas</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/jquery/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQueryUI CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jqueryui/jquery-ui-1.10.4/css/smoothness/jquery-ui-1.10.4.custom.css\" />\n");
      out.write("\n");
      out.write("<!-- JQueryUI -->\n");
      out.write("<script src=\"lib/jqueryui/jquery-ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQUERY Scrollbar -->\n");
      out.write("<script src=\"lib/scrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- MD5 -->\n");
      out.write("<script src=\"lib/md5/md5.js\"></script>\n");
      out.write("\n");
      out.write("<!-- DATATABLE -->\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/datatable/datatable-1.10.2/css/jquery.dataTables.min.css\" />\n");
      out.write("<script src=\"lib/datatable/datatable-1.10.2/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/globals.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/admin/manager.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- ICONS STYLE (FONT-AWESOME + EXTRA CUSTOM FONTS ICON) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-awesome.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons/css/font-extra-icon.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!--Dragging secure Utils -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragging_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  Validator -->\n");
      out.write("<script type=\"text/javascript\" src=\"lib/validation/validation-1.13.1/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/validate/Validate.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Login -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/login/LoginUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- General Scripts -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/LoadingPanel.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/utils/Utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/Services.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/AlertDialog.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/DialogUtils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/dragdrop_utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/sorting_utils.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Scripts - Locale -->\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/LocaleManager.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_en.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/locale/locale_es.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminMenu.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/admin/AdminUtils.js\"></script>\n");
      out.write("\n");
      out.write("<!--  General CSS -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/admin/general.css\" type=\"text/css\"> -->\n");
      out.write("<script>\n");

	/*
	* LANGUAGE
	*/
	String languageCode = LoginService.getCurrentLanguageFromSessionOrDefault(session);

	/*
	* GLOBAL VARIABLES
	*/
	 String jsonGlobalSettings = new SystemSettingService().getClientSystemSettingsAsJson();

      out.write("\n");
      out.write("var globalSystemSettingsJson =");
      out.print(jsonGlobalSettings);
      out.write(";\n");
      out.write("var GLOBAL_SETTINGS = globalSystemSettingsJson.result;\n");
      out.write("LocaleManager.setLocale(\"");
      out.print(languageCode);
      out.write("\");\n");
      out.write("\n");
      out.write("var AJAX_TIMEOUT = GLOBAL_SETTINGS.ajaxTimeout;\n");
      out.write("\n");
      out.write("</script>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/admin/managerUsers.css\" type=\"text/css\"> -->\n");
      out.write("\n");
      out.write("<!-- Start script -->\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t//Move the testRequestContainer into the BodyContent\n");
      out.write("\t\t//var testRequestContainer = $(\"#testRequestContainer\");\n");
      out.write("\t\t//testRequestContainer.detach();\n");
      out.write("\t\t\n");
      out.write("\t\t//$(\".center-container\").append(testRequestContainer);\n");
      out.write("\t\t\n");
      out.write("\t\tLocaleManager.refreshLocale();\n");
      out.write("\t\tAdminMenu.setTestRequestsPageActive();\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#requests-refresh\").button();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction loadRequest() {\n");
      out.write("\t\tvar selectedRequest = $(\"#select-requests\").find(\":selected\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar url = './mapConfig';\n");
      out.write("\t\tif (\"exportExternalWmsServersAsJson\" === selectedRequest.val()) {\n");
      out.write("\t\t\turl = './systemConfig';\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : url,\n");
      out.write("\t\t\ttype : 'POST',\n");
      out.write("\t\t\t//dataType : 'json',\n");
      out.write("\t\t\tdata : {\n");
      out.write("\t\t\t\toper : selectedRequest.val()\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}).done(function(response) {\n");
      out.write("\t\t\t$(\"#request_result\").val(response);\n");
      out.write("\t\t}).fail(function(jqXHR, textStatus, error){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif (Utils.isEmpty(error)) {\n");
      out.write("\t\t\t\terror = LocaleManager.getKey(\"Ajax_General_Error\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tAlertDialog.createOkDefaultDialog(\n");
      out.write("\t\t\t\tLocaleManager.getKey(\"AlertDialog_Error_Title\"), \n");
      out.write("\t\t\t\terror,\n");
      out.write("\t\t\t\t\"error\"\n");
      out.write("\t\t\t);\n");
      out.write("\t\t}).error(function(jqXHR, textStatus, error){\n");
      out.write("\t\t\tif (Utils.isEmpty(error)) {\n");
      out.write("\t\t\t\terror = LocaleManager.getKey(\"Ajax_General_Error\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tAlertDialog.createOkDefaultDialog(\n");
      out.write("\t\t\t\tLocaleManager.getKey(\"AlertDialog_Error_Title\"), \n");
      out.write("\t\t\t\terror,\n");
      out.write("\t\t\t\t\"error\"\n");
      out.write("\t\t\t);\t\t\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t#testRequestContainer {\n");
      out.write("\t\tpadding: 15px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fgeneric_005fadmin_005fpage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:generic_admin_page
    org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0 = (new org.apache.jsp.tag.webgeneric_005fadmin_005fpage_tag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspContext(_jspx_page_context);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_test_requests.jsp(84,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setHeader(_jspx_temp0);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null);
    // /WEB-INF/jsp/admin/admin_test_requests.jsp(84,1) null
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setFooter(_jspx_temp1);
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0, null));
    _jspx_th_t_005fgeneric_005fadmin_005fpage_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fgeneric_005fadmin_005fpage_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("\t\t\t<div id=\"testRequestContainer\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<p><b>Pruebas de llamadas</b></p>\n");
      out.write("\t\t\t<p>Seleccionar: \n");
      out.write("\t\t\t<select id=\"select-requests\">\n");
      out.write("\t\t\t\t<option value=\"exportConfigAsJson\">exportConfigAsJson</option>\n");
      out.write("\t\t\t\t<option value=\"exportMapConfigAsJson\">exportMapConfigAsJson</option>\n");
      out.write("\t\t\t\t<option value=\"exportGroupConfigAsJson\">exportGroupConfigAsJson</option>\n");
      out.write("\t\t\t\t<option value=\"exportLayerServicesListAsJson\">exportLayerServicesListAsJson</option>\n");
      out.write("\t\t\t\t<option value=\"exportExternalWmsServersAsJson\">exportExternalWMSAsJson</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<button id=\"requests-refresh\" data-locale_key=\"General_Refresh\" data-locale_ref=\"text\" class=\"localizedElement\" onclick=\"loadRequest();\"></button>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<textarea readonly=\"readonly\" style=\"width:100%;height:50em;font-size:small\" name=\"request_result\" id=\"request_result\">\n");
      out.write("\t\t\t</textarea>\n");
      out.write("\t</div>\n");
      out.write("\t\t");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
